ManaBingsu 2주차 풀이완료
PMM-Dev/algo-study pull request #7
Opened 2020-12-15 07:21 UTC by ManaBingsu

2020-12-16 14:07 UTC, Kwon770 approved these changes

2020-12-16 14:07 UTC, Kwon770 commented on algorithm/week2/ManaBingsu_PS/week2_kwon770_1.cpp
> +		check[i] = isMatch ? 1 : 0;
코드가 전체적으로 저와 같은데, 이부분만 다르네요.
check 배열을 char 형으로 선언하고 그에따라 문자를 할당하면, 32번줄의 코드도 필요없고 시간도 줄고 메모리도 줄 것입니다.
코드상은 그런데, 왜 내꺼 메모리가 더 많이 들지..? 헤더때문인가.

2020-12-16 14:07 UTC, Kwon770 commented on algorithm/week2/ManaBingsu_PS/week2_sjmjys954646_1.cpp
> +		spectrum = str[index++] == '@' ? spectrum + 1 : spectrum;
인덱싱 내 ++ 의 위치에 따른 동작 설명 요청할 예정입니다.

2020-12-16 14:07 UTC, Kwon770 commented on algorithm/week2/ManaBingsu_PS/week2_sjmjys954646_1.cpp
> +	return 0;
while을 통해 흐름을 진행하는건 뭔가 아쉽네요. for 문을 통해 문자열을 훑는게 코드적으로도 더 간단할꺼라 생각합니다.

2020-12-16 14:07 UTC, Kwon770 commented on algorithm/week2/ManaBingsu_PS/week2_kwon770_2.cpp
> +	if (isWord)
48번 뒤집기줄이 따로 빠져나와있는거와 isTag isWord 두 개나 상태 변수로 둔 것은 어떤 예외를 상정한것인지 설명 요청할 예정입니다.

2020-12-16 14:07 UTC, Kwon770 commented on algorithm/week2/ManaBingsu_PS/week2_ManaBingsu.cpp
> +		for (int j = pSize - 1; j >= i; j--) {
i ~ j 까지의 문자열을 뽑아서 find 하고, j는 제일 뒤부터 인덱싱을 하는 것으로 보이는데 맞나요?

2020-12-17 08:09 UTC, sjmjys954646 requested changes

2020-12-17 08:09 UTC, sjmjys954646 commented on algorithm/week2/ManaBingsu_PS/week2_kwon770_2.cpp
> +
이 문제는 저도 풀어 봤는데 코드가 너무 복잡하니 리뷰 안하겠습니다.
알고리즘 자체는 비슷하네요

2020-12-17 08:09 UTC, sjmjys954646 commented on algorithm/week2/ManaBingsu_PS/week2_sjmjys954646_1.cpp
> +
@===@==@=@==(^0^)==@=@===@
태보태보 총난타!

2020-12-17 08:09 UTC, sjmjys954646 commented on algorithm/week2/ManaBingsu_PS/week2_sjmjys954646_2.cpp
> +		string buffer;
이 부분 입력스트림 비워주는건가요?
주석처리 나니까 입력을 못받던데

2020-12-17 12:46 UTC, sjmjys954646 approved these changes

2020-12-17 13:19 UTC, merged